version: '2'

services:

  namelessmc:
    image: derkades/namelessmc-nginx
    ports: ['80:80']
    volumes: ['/srv/namelessmc/web:/data']
    # environment:
    #   PHP_FPM: namelessmc_php:9000
    depends_on: [namelessmc_php]
    restart: unless-stopped

  namelessmc_php:
    image: derkades/namelessmc-php
    volumes_from: [namelessmc]
    restart: unless-stopped

  namelessmc_db:
    image: mariadb
    volumes: ['/srv/namelessmc/db:/var/lib/mysql']
    environment:
      MYSQL_ROOT_PASSWORD: nameless
      MYSQL_USER: nameless
      MYSQL_PASSWORD: nameless
      MYSQL_DATABASE: nameless
    restart: unless-stopped
