version: '2'

services:

  namelessmc:
    build: nginx_web
    ports: ['80:80']
    volumes: ['/srv/namelessmc/web:/data'] # same as php container
    depends_on: [namelessmc_php]

  namelessmc_php:
    build: php_fpm
    volumes: ['/srv/namelessmc/web:/data'] # same as web container

  namelessmc_db:
    image: mariadb
    volumes: ['/srv/namelessmc/db:/var/lib/mysql']
    environment:
      MYSQL_ROOT_PASSWORD: nameless
      MYSQL_USER: nameless
      MYSQL_PASSWORD: nameless
      MYSQL_DATABASE: nameless
