version: '2'

services:

  nginx:
    image: namelessmc/nginx
    ports: ['80:80']
    volumes: ['/srv/namelessmc/web:/data'] # same as php container
    # environment:
    #   PHP_FPM: php:9000
    depends_on: [php]
    restart: unless-stopped

  php:
    image: namelessmc/php
    volumes: ['/srv/namelessmc/web:/data'] # same as web container
    restart: unless-stopped

  db:
    image: mariadb
    volumes: ['/srv/namelessmc/db:/var/lib/mysql']
    environment:
      MYSQL_ROOT_PASSWORD: nameless
      MYSQL_USER: nameless
      MYSQL_PASSWORD: nameless
      MYSQL_DATABASE: nameless
    restart: unless-stopped
